# （十二）JAVA 异常处理

## 1. 异常概述与异常体系结构

### 1.1 异常概述

- **异常**：在Java语言中，将程序执行中发生的不正常情况称为“异常”（开发过程中的语法错误和逻辑错误不是异常）
- Java程序在执行过程中所发生的异常事件可 **分为两类**：
    - <font color=red>Error</font>: Java虛拟机无法解决的严重问题。如: JVM系统内部错误、资源耗尽等严重情况。比如: StackOverflowError和OOM。 一般不编写针对性的代码进行处理。
    - <font color=red>Exception</font>：其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如:
        - **空指针访问**
        - **试图读取不存在的文件**
        - **网络连接中断**
        - **数组角标越界**

- 对于这些错误，一般有两种解决方法：
    - 一种是遇到错误就终止程序的运行。
    - 另种方法是由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。
- 捕获错误最理想的是在编译期间，但有的错误只有在运行时才会发生。        
    比如:除数为0，数组下标越界等
- 分类：编译时异常和运行时异常

### 1.2 异常体系结构

```
java.lang.Throwable
    |---java.lang.Error: 一般不编写针对性的代码进行处理。
    |---java.lang.Exception: 可进行异常处理
        |---编译时异常（checked）
            |---IOEException
                |---FileNotFoundException
            |---ClassNotFoundException
        |---运行时异常（unchecked）
            |---NullPointerException
            |---ArrayIndexOutOfBoundException
            |---ClassCastException
            |---NumberFormatException
            |---InputMismatchException
            |---ArithmaticException
```

## 2. 常见异常

```java
import org.junit.Test;
import java.util.Date;
import java.util.Scanner;

public class Test1 {
    //运行时异常（unchecked）
    //NullPointerException
    @Test
    public void test1() {
        String str = null;
        System.out.println(str.charAt(0));
    }
    //ArrayIndexOutOfBoundsException
    @Test
    public void test2() {
        Integer[] arr = new Integer[3];
        System.out.println(arr[3]);
    }
    //ClassCastException
    @Test
    public void test3() {
        Object obj = new Date();
        String str = (String) obj;
    }
    //NumberFormatException
    @Test
    public void test4() {
        String str = "12345a";
        System.out.println(Integer.parseInt(str));
    }
    //InputMismatchException
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int x = in.nextInt();
        System.out.println(x);
    }
    //ArithmaticException
    @Test
    public void test6() {
        System.out.println(1 / 0);
    }
}

```

## 3. 异常处理机制一：try-catch-finally
## 4. 异常处理机制二：throws
## 5. 手动抛出异常：throw
## 6. 用户自定义异常类